
setup() {
  
  SESSION_DIR="$(mktemp -d)"
  SESSION_CREATE_HEADERS="$SESSION_DIR/create"
  SESSION_UPLOAD_HEADERS="$SESSION_DIR/upload_headers"
  SESSION_UPLOAD_BODY="$SESSION_DIR/upload_body"
  SESSION_STATUS_HEADERS="$SESSION_DIR/status"
  SESSION_REFRESH_TOKEN_HEADERS="$SESSION_DIR/token_headers"
  SESSION_REFRESH_TOKEN_BODY="$SESSION_DIR/token_body"
}